# Generated by Django 5.0.2 on 2024-03-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('ICT Dept', 'ICT Department'), ('Procurement', 'Procurement'), ('HR', 'Human Resource')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('nairobi', 'Nairobi HQ'), ('coast', 'Coast'), ('rift_valley', 'Rift Valley'), ('kisumu', 'Kisumu'), ('estern', 'Estern')], max_length=100),
        ),
    ]
