# Generated by Django 5.0.2 on 2024-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_department_alter_customuser_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='visitee_name',
        ),
        migrations.AddField(
            model_name='entry',
            name='visitees',
            field=models.CharField(choices=[('one', 'One'), ('one', 'Two'), ('one', 'Three')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT Department'), ('Procurement', 'Procurement'), ('Human Resource', 'Human Resource'), ('Finance', 'Finance'), ('Legal', 'Legal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('1', 'Nairobi HQ'), ('2', 'Coast'), ('3', 'Rift Valley'), ('4', 'Kisumu'), ('5', 'Estern')], max_length=100),
        ),
    ]
