# Generated by Django 5.0.2 on 2024-03-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_entry_visitee_name_entry_visitees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='email',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='visitees',
        ),
        migrations.AddField(
            model_name='entry',
            name='nature_of_visit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='visitee',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
