# Generated by Django 5.0.2 on 2024-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_email_entry_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
