# Generated by Django 5.0.2 on 2024-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_entry_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
