# Generated by Django 5.0.2 on 2024-03-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_entry_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id_number',
        ),
    ]
