# Generated by Django 5.0.2 on 2024-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_entry_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.CharField(blank=True, default='Type Comment...', max_length=255),
        ),
    ]
