# Generated by Django 5.0.2 on 2024-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_entry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sign_out',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
