# Generated by Django 5.0.2 on 2024-03-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_entry_sign_out_alter_entry_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sign_out',
            field=models.BooleanField(default=False),
        ),
    ]
