# Generated by Django 5.0.2 on 2024-03-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_entry_sign_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='sign_out',
            new_name='is_signedout',
        ),
    ]
