# Generated by Django 5.0.2 on 2024-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_sign_out_entry_is_signedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
