# Generated by Django 5.0.2 on 2024-03-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_entry_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='id_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
