# Generated by Django 5.0.2 on 2024-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_entry_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
