# Generated by Django 5.0.2 on 2024-04-17 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='receptionist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
