# Generated by Django 5.0.2 on 2024-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_customuser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
