# Generated by Django 5.0.2 on 2024-05-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_group_groupmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='plate_number',
            new_name='plate_number2',
        ),
    ]
