# Generated by Django 5.0.2 on 2024-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_plate_number_group_plate_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
