# Generated by Django 5.0.2 on 2024-05-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_group_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='checked',
            new_name='is_checked',
        ),
    ]
