# Generated by Django 5.0.2 on 2024-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_checked_group_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
