# Generated by Django 5.0.2 on 2024-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_group_created_at_groupmember_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
