# Generated by Django 5.0.2 on 2024-05-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_group_receptionist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='receptionist',
        ),
    ]
